#ifndef CONFIG_H
#define CONFIG_H

#define SUPERCLIP_PREFIX "/usr/local"
#define SUPERCLIP_MAX_RECORD 65536U
#define SUPERCLIP_MAX_ITEMS 256U
#define SUPERCLIP_MAX_QUERY 65500U
#define SUPERCLIP_MAX_STDERR 4096U
#define SUPERCLIP_DEBOUNCE_MS 50
#define SUPERCLIP_CHILD_GRACE_MS 200

#define SUPERCLIP_FONT "monospace:size=12"
#define SUPERCLIP_FALLBACK_FONT "Noto Sans Mono CJK SC:size=12"
#define SUPERCLIP_FOREGROUND "#e6e6e6"
#define SUPERCLIP_BACKGROUND "#202020"
#define SUPERCLIP_SELECTED "#3a6ea5"
#define SUPERCLIP_PROMPT "#7aa2cc"
#define SUPERCLIP_WIDTH 900
#define SUPERCLIP_PADDING 16
#define SUPERCLIP_VISIBLE_ROWS 12

#endif
