#ifndef CONFIG_H
#define CONFIG_H

#define SUPERCLIP_PREFIX "/usr/local"
#define SUPERCLIP_MAX_RECORD 65536U
#define SUPERCLIP_MAX_ITEMS 256U
#define SUPERCLIP_MAX_QUERY 65500U
#define SUPERCLIP_MAX_STDERR 4096U
#define SUPERCLIP_DEBOUNCE_MS 50
#define SUPERCLIP_CHILD_GRACE_MS 200

#define SUPERCLIP_FONT "monospace:size=12"
#define SUPERCLIP_FALLBACK_FONT "Noto Sans Mono CJK SC:size=12"
#define SUPERCLIP_WIDTH 640
#define SUPERCLIP_PADDING 12
#define SUPERCLIP_VISIBLE_ROWS 8

#endif
